lorem/lorem/urls.py
from django.conf.urls import patterns, include, url

#from userstats.signals import *

import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from catalog import views as adv
#from tuhes_basket import views as basket
from pages import views as pgs
#from userstats import views as us
from filebrowser.sites import site
#from feedback.views import feedback
admin.autodiscover()
from django_summernote.views import editor, upload_attachment

#from menuz import registry
#registry.autodiscover()




urlpatterns = patterns('',
#   (r'^summernote/', include('django_summernote.urls')),	
url(r'^redactor/', include('redactor.urls')),
(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
  #  url(r'', include('menuz.urls')),
    #url (r'^basket/',basket.view),    
    #url (r'^feedback/',feedback),

    #url(r'^accounts/register/', us.registration),
    
    # Examples:
    # url(r'^$', 'lorem.views.home', name='home'),
    # url(r'^lorem/', include('lorem.foo.urls')),

    # Uncomment the admin/doc line below to enable admin 
    #documentation:
    url(r'tag/(.*)/',adv.tag),
    url(r'random/',adv.rand),
    url(r'^boobs/(.*)',adv.item),
    url(r'^search/*', adv.search),
    # url(r'^Item/up/(\d*)/', adv.up),
    #url(r'^Item/delete/(\d*)/', adv.delete),
    #url(r'^warring/', us.setWarring),
    url(r'^page/(.*)/', pgs.page),
    #url(r'^profile/(.*)/', us.profile),

      
    #url(r'^Items/add', adv.add),
    #url(r'^category/(.*)/', adv.category),    
    #url(r'^catalog/items/(\d*)/', adv.Item),    
    #url(r'^city/(\d*)/', adv.setcity),    
    url(r'^accounts/', include('registration.backends.default.urls')),
	url('foundation', include('foundation.urls')),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^admin/filebrowser/', include(site.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url('', adv.index),
)

lorem/catalog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django_thumbs.db.models import ImageWithThumbsField
from autoslug.fields import AutoSlugField
#для миграций превьюшек
from south.modelsinspector import add_introspection_rules
from django.forms import ModelForm
#from myadpp.models import Article
#from mptt.models import MPTTModel, TreeForeignKey

from redactor.fields import RedactorField

#from lib.thumbs import ImageWithThumbsField
if 1:
    add_introspection_rules([
        (
            [ImageWithThumbsField], # Class(es) these apply to
            [],         # Positional arguments (not used)
            {           # Keyword argument
                "sizes": ["sizes", {}],
            },
        ),
    ], ["^django_thumbs\.db\.models\.ImageWithThumbsField"])




class Tag(models.Model):
    title = models.CharField(max_length=255)
    alias = AutoSlugField(max_length=255)
    tag   = models.ForeignKey('self', null = True, blank = True, related_name="Parent Tag")
    def __unicode__(self):
        return self.title




class Item(models.Model):
	mainPhoto	=	ImageWithThumbsField(upload_to='images', sizes=((125,125),(300,300)), blank=True, verbose_name=u"Фото")
	title		=	models.CharField(max_length=255, verbose_name=u"Заголовок")
	alias		=	AutoSlugField(populate_from='title')
	text		=	RedactorField(verbose_name=u"Описание")
	pub_date	=	models.DateTimeField(auto_now_add = True, verbose_name=u"Дата создания")
	upd_date	=	models.DateTimeField(auto_now_add = True, verbose_name=u"Дата изменения1")
	tags            =       models.ManyToManyField(Tag)
        html_title      =       models.TextField(max_length=255,verbose_name="Заголовок страницы", null=True, blank=True)
        html_description=       models.TextField(max_length=255,verbose_name="Описание страницы", null=True, blank=True)
        meta_keywords   =       models.TextField(max_length=255,verbose_name="meta_keywords", null=True, blank=True)
        item_type       =       models.CharField(max_length=255,verbose_name="Тип статьи",choices = (('n','Новая'),('g','Хорошая'),('b','Лучшая')), default='n');
	def __unicode__(self):
		return self.title
        def get_absolute_url(self):
            return "/boobs/%s" % self.alias
	class Meta:
		verbose_name = " Сиськи "
		verbose_name_plural = " Сиськи  "
    

class InfoCategory(models.Model):
    title = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    def __unicode__(self):
        return self.title

class InfoValue(models.Model):
    value       = models.CharField(max_length=255)
    category    = models.ForeignKey(InfoCategory,)
    item        = models.ForeignKey(Item,)
#class AdvertismentForm(ModelForm):
#	class Meta:
#		model	=	Item
#		fields	=	['category','mainPhoto','title','text']

lorem/templates/advertisments/add.html
{% extends "base.html" %}
{% block foundation_body %}
{% load category_tags %}
<style>
.cat {display:none;}
</style>

<script type='text/javascript'>
$(document).ready( function() {
$('#id_category').on('change', function() {
					$('.cat').hide();
					$('.cat'+this.value).show();
					  //alert( '.cat'+this.value ); // or $(this).val()
					});
});					
</script>
	
	
		
		
	
	<div class="columns large-7">
		
			<form enctype="multipart/form-data"  
action="/advertisments/add/" method="post">
			{% csrf_token %}
			  <fieldset>
				<legend>Добавление объявления</legend>
				
				<div class="row collapse">
					 {% for field in form %}
						<div class="small-2 columns">
						<span class="left prefix"
							{{ field.label_tag }}
						</span>
						</div>
						
						<div class="small-10 columns">
						{{ field }}
						</div>
					 {% endfor %}
						<h6> Дополнительные поля </h6>
					{% for field in additionalFields %}
					<div class="cat  {% for i in field.category.all %}cat{{ i.id }} {% endfor %} row collapse">
					<div class="small-2 columns">
						<span class="left prefix">
							{{ field.name }}
						</span>	
					</div>
					<div class="small-10 columns">
						<input type=text name='additionalField{{ field.id }}'>
					</div>
					</div>
					{% endfor %}
				
					<!--
					<div class="small-2 columns">
						<span class="left prefix">Город</span>
					</div>
					<div class="small-10 columns">
						<input type="text" placeholder="">
					</div>
					<div class="small-2 columns">
						<span class="left prefix">Категория</span>
					</div>
					<div class="small-10 columns">
						<input type="text" placeholder="">
					</div>
					<div class="small-2 columns">
						<span class="left prefix">Заголовок</span>
					</div>
					<div class="small-10 columns">
						<input type="text" placeholder="">
					</div>
					<div class="small-2 columns">
						<span class="left prefix">Фото</span>
					</div>
					<div class="small-10 columns">
						<input type="text" placeholder="">
					</div>
					<div class="small-12 columns">
						<textarea> </textarea>
					</div>-->
					
					
					
					<div class="small-2 columns">
						<input type="submit" class="button prefix" value="Разместить">
					</div>
				</div>
			  </fieldset>
			</form>
		
	</div>
	



{% endblock foundation_body %}

lorem/templates/advertisments/index.html
{% extends "base.html" %}
{% load category_tags %}
{% block foundation_body %}

	

		
	
	<div class="columns large-7">
		
		{% for item in items %}
			<div class='columns large-12 panel'>
				<h6> {{ item.title }} </h6>
				<div class='columns large-2'>
					<a class="fancybox" title="{{ item.title }}" rel="group" href="/media/{{ item.mainPhoto }}"><img title="{{ item.title }}" src="{{ item.mainPhoto.url_300x300 }}" alt="{{ item.title }}" /></a>
				</div>
				<div class='columns small-10'>
					<small>{{ item.text }}</small>
						<br/>
						<br/>
						<a href="/catalog/items/{{ item.id }}/">Подробрнее</a>
					</div>
			</div>
		{% endfor %}
		
		
		
		
	<ul class="pagination">
		<li class="arrow {% if offset = '0' %}unavailable {% endif %}"><a href="?page={{ offset|add:-1 }}">&laquo;</a></li>
		
		{% for i in count %}
		
			{% if count|length > 10 and i > 4   %}			
				{% if offset = i %}
					<li class="current"><a href="#">{{ i }}</a></li>
				{% else %}			
		
						{% if i|add:3 > count|length %}
							<li class=""><a href="?page={{ i }}">{{ i }}</a></li>
						{% endif %}
					
				{% endif %}
				
							{% if count|length > 10 and i = 5  %}
					 <li class="unavailable"><a href="#">&hellip;</a></li>
					{% endif %}
			{% else %}
			
			<li class="{% if i = offset %}current {% endif %}"><a href="?page={{ i }}">{{ i }}</a></li>
			
			{% endif %}
		{% endfor %}
		<li class="arrow {% if offset = count|last %}unavailable {% endif %}"><a href="?page={{ offset|add:1 }}">&raquo;</a></li>
	</ul>

	</div>
	
		


{% endblock foundation_body %}

lorem/templates/advertisments/item.html
{% extends "base.html" %}
{% load category_tags %}
{% block foundation_body %}

	
	
	
	<div class="columns large-10">
			
			
			<div class='columns large-9'>
				<h6> {{ item.title }} </h6>
                <hr/>
                <div class="item-content">
                    {{ item.text|safe }}
                </div>

            </div>
            <div class='columns large-3'>
			
				
				<div style="text-align:center;" class='panel columns large-12'>
					{% if item.mainPhoto %}
					<img src='{{ item.mainPhoto.url }}'> 
					{% endif %}
				</div>
							
				
				<div class='columns small-12 panel'>
						{% for p in item.additional_info %}
							 {{ p.category.title }}:
							 {{ p.value }} 
                             <br/>
						{% endfor %}
					
						
					</div>
			
				
			
			</div>
		
			<div class="columns large-12">
            <strong>Тэги: </strong>
            {% for tag in item.tags.all %}
                {{ tag.title }} 
            {% endfor %}
        </div>	
	</div>
	



{% endblock foundation_body %}

lorem/templates/advertisments/search_result.html
{% extends "base.html" %}
{% block foundation_body %}
{% load category_tags %}
<div class="columns large-10">
    <div class="panel columns large-12">
        <h3>Результаты поиска</h3>
    </div>

    <div class="columns large-12">
        {% for item in items %}
        <div class="">
            <h4><a href="/boobs/item.slug">{{ item.title }} </a></h4>
            <p> {{ item.text|striptags|slice:"200" }}...
        </div>
        {% endfor %}
    </div>


</div>    

{% endblock foundation_body %}